import {spawn} from 'node:child_process';
import {readFileSync,readdirSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,basename,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {WASI} from 'node:wasi';
const root=resolve(import.meta.dirname,'../..');
const sdk=process.env.WASI_SDK_ROOT||'D:/workspace/eagler/toolchains/wasi-sdk-34.0-x86_64-windows';
const compiler=resolve(sdk,'bin/clang++.exe');
const out=resolve(root,'artifacts/multiplayer-native');mkdirSync(out,{recursive:true});
const walk=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(resolve(dir,e.name)):[resolve(dir,e.name)]);
const all=walk(resolve(root,'th11_web/cpp/game'));
const sources=[...all.filter(p=>p.endsWith('.cpp')),resolve(import.meta.dirname,'native-gameplay.cpp')];
const headers=[...all.filter(p=>/\.(hpp|inc)$/.test(p)),...walk(resolve(root,'portable/sdl')).filter(p=>p.endsWith('.hpp')),...walk(import.meta.dirname).filter(p=>p.endsWith('.hpp')&&basename(p).startsWith('native-'))];
const hash=b=>createHash('sha256').update(b).digest('hex');
const flags=['--target=wasm32-wasip1','-std=c++17','-O1','-g0','-DTH11_MULTIPLAYER=1','-ffp-contract=off','-fno-strict-aliasing','-fno-exceptions','-fno-rtti'];
const headerKey=hash(headers.sort().map(p=>p+hash(readFileSync(p))).join('\n'));
const run=args=>new Promise((accept,reject)=>{const child=spawn(compiler,args,{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';child.stdout.on('data',b=>log+=b);child.stderr.on('data',b=>log+=b);child.on('error',reject);child.on('exit',code=>code?reject(Error(log)):accept());});
let cursor=0;const objects=new Array(sources.length);
await Promise.all(Array.from({length:4},async()=>{while(cursor<sources.length){const i=cursor++,file=sources[i],object=resolve(out,basename(file)+'.o'),key=hash(JSON.stringify([flags,headerKey,hash(readFileSync(file))]));if(!existsSync(object)||!existsSync(object+'.key')||readFileSync(object+'.key','utf8')!==key){await run([...flags,'-c',file,'-o',object]);writeFileSync(object+'.key',key);}objects[i]=object;}}));
const wasm=resolve(out,'native-gameplay.wasm');await run([...flags,...objects,'-Wl,-z,stack-size=2097152','-Wl,--max-memory=1073741824','-o',wasm]);
const archive=process.env.TH11_TEST_ARCHIVE||resolve(root,'../../th11-eagler/[th11] 东方地灵殿 (汉化版+日文版)/th11.dat');
if(!existsSync(archive))throw Error('Set TH11_TEST_ARCHIVE to the existing legally supplied th11.dat fixture');
const testMode=['presentation','restart','repair','risk','ui','score'].find(mode=>process.argv.includes('--'+mode));
const wasi=new WASI({version:'preview1',args:['native-gameplay','/assets/'+basename(archive),...(testMode?[testMode]:[])],preopens:{'/assets':dirname(archive)},returnOnExit:true});
const instance=await WebAssembly.instantiate(await WebAssembly.compile(readFileSync(wasm)),{wasi_snapshot_preview1:wasi.wasiImport});
process.exitCode=wasi.start(instance);
