// Generated from purple thprac_games_def.json (MIT).
#pragma once
namespace th11 {
inline constexpr const char* practice_TH_MENU[3]{"练习选项","Option","オプション"};
inline constexpr const char* practice_TH_PHASE[3]{"阶段","Phase","段階"};
inline constexpr const char* practice_TH_11_WAVE_PASSED_DESC[3]{"全避道中一非约%d，\n全避一二非约%d，\n全避一非猫步一波约%d，\n全避一二非猫步一波约%d","Timing out mid NS 1:~%d;\n Timing out mid NS 1 2:~%d;\nTiming out mid NS 1, 1 wave cat walk:%d;\nTiming out mid NS 1 2, 1 wave cat walk:%d\n","Timing out mid NS 1:~%d;\n Timing out mid NS 1 2:~%d;\nTiming out mid NS 1, 1 wave cat walk:%d;\nTiming out mid NS 1 2, 1 wave cat walk:%d\n"};
inline constexpr const char* practice_TH_STAGE_PORTION_N[3]{"#%d","#%d","#%d"};
inline constexpr const char* practice_TH_STAGE_PORTION_1[3]{"前半 #%d","First Half #%d","前半 #%d"};
inline constexpr const char* practice_TH_STAGE_PORTION_2[3]{"后半 #%d","Second Half #%d","後半 #%d"};
inline constexpr const char* practice_TH_MODE[3]{"模式","Mode","モード"};
inline constexpr const char* practice_TH_STAGE[3]{"关卡","Stage","ステージ"};
inline constexpr const char* practice_TH_WARP[3]{"传送","Warp","ワープ"};
inline constexpr const char* practice_TH11_MARISAB_FORMATION_LABEL[3]{"配置","Formation","配置"};
inline constexpr const char* practice_TH_DLG[3]{"对话","Dialog","ダイアログ"};
inline constexpr const char* practice_TH_CHAPTER[3]{"章节","Chapter","チャプター"};
inline constexpr const char* practice_TH_LIFE[3]{"残机","Life","残機"};
inline constexpr const char* practice_TH_LIFE_FRAGMENT[3]{"残机碎片","Life Frag.","残機の欠片"};
inline constexpr const char* practice_TH_GRAZE[3]{"擦弹","Graze","グレイズ"};
inline constexpr const char* practice_TH_POWER[3]{"火力","Power","霊力"};
inline constexpr const char* practice_TH_SCORE[3]{"分数","Score","スコア"};
inline constexpr const char* practice_TH_FAITH[3]{"信仰","Faith","信仰"};
inline constexpr const char* practice_TH11_SPELL_CATEGORY[3]{"想起","Spell Cat.","スペル種類"};
inline constexpr const char* practice_TH_BOSSX[3]{"BossX","BossX","BossX"};
inline constexpr const char* practice_TH_BOSSY[3]{"BossY","BossY","BossY"};
inline constexpr const char* practice_TH_11_WAVE_PASSED[3]{"经过的波数","waves passed","waves passed"};
inline constexpr const char* practice_TH_MID_STAGE[3]{"道中Boss","Mid Boss","道中ボス"};
inline constexpr const char* practice_TH_END_STAGE[3]{"关底Boss","End Boss","ボス"};
inline constexpr const char* practice_TH_NONSPELL[3]{"非符","Non Spell","通常"};
inline constexpr const char* practice_TH_SPELL[3]{"符卡","Spell Card","スペカ"};
inline constexpr const char* practice_TH_MUTEKI[3]{"无敌","Invincible","無敵"};
inline constexpr const char* practice_TH_INFPOWER[3]{"锁火力","Inf. Power","霊力減らない"};
inline constexpr const char* practice_TH_AUTOBOMB[3]{"自动B","Auto Bomb","自動喰らいボム"};
inline constexpr const char* practice_TH_INFLIVES2[3]{"锁残/不疮","Inf. Lives/No Continue","残機減らない/No Continue"};
inline constexpr const char* practice_TH_TIMELOCK[3]{"锁时","Time Lock","残り時間減らない"};
inline constexpr const char* practice_TH_EL_BGM[3]{"永续BGM","Everlasting BGM","永遠に続くBGM"};
inline constexpr const char* practice_THPRAC_INGAMEINFO[3]{"更多游戏信息","in game info","in game info"};
inline constexpr const char* practice_TH_ENEMY_MUTEKI[3]{"敌人无敌","Enemy Invincible","敵無敵"};
inline constexpr const char* practice_THPRAC_INGAMEINFO_MISS_COUNT[3]{"miss:","miss:","miss:"};
inline constexpr const char* practice_THPRAC_INGAMEINFO_BOMB_COUNT[3]{"bomb:","bomb:","bomb:"};
inline constexpr const char* practice_TH_SPELL_PRAC[3]{"符卡练习","Spell Practice","スペルプラクティス"};
inline constexpr const char* practice_TH_ADV_OPT[3]{"高级选项","Advanced Options","拡張オプション"};
inline constexpr const char* practice_TH_GAME_SPEED[3]{"游戏速度","Game Speed","ゲームの速度"};
inline constexpr const char* practice_TH_GAMEPLAY[3]{"游戏进行","Gameplay","ゲームプレイ"};
inline constexpr const char* practice_THPRAC_INGAMEINFO_TH11_SHOW_HINT[3]{"显示hint","show hint","show hint"};
inline constexpr const char* practice_THPRAC_INGAMEINFO_ADV_DESC1[3]{"部分功能需要打开更多游戏信息(backspace菜单)中的选项开启","need to enable ingameinfo(in backspace menu) to show","need to enable ingameinfo(in backspace menu) to show"};
inline constexpr const char* practice_THPRAC_INGAMEINFO_ADV_DESC2[3]{"免责声明: 部分功能可能会被认为是作弊","disclaimer: might be considered as cheating","disclaimer: might be considered as cheating"};
inline constexpr const char* practice_TH_BOSS_FORCE_MOVE_DOWN[3]{"完全下压","force boss region to move down","force boss region to move down"};
inline constexpr const char* practice_TH_BOSS_FORCE_MOVE_DOWN_DESC[3]{"只给练习用，会对rep造成影响注意，基于原理对部分boss有bug","for practice, it will affect the rep, buggy for some bosses","for practice, it will affect the rep, buggy for some bosses"};
inline constexpr const char* practice_TH_BOSS_FORCE_MOVE_DOWN_RANGE[3]{"下压幅度","range","range"};
inline constexpr const char* practice_TH_DISABLE_MASTER[3]{"符卡收率完整显示","show complete spellcard capture rate","show complete spellcard capture rate"};
inline constexpr const char* practice_TH_DISABLE_MASTER_DESC[3]{"不显示master 0/99+等","no master, 0/99+, etc","no master, 0/99+, etc"};
inline constexpr const char* practice_TH11_MARISAB_LOCK[3]{"锁定魔B配置","Lock Marisa B Formation","Lock Marisa B Formation"};
inline constexpr const char* practice_TH11_MARISAB_LOCK_DESC[3]{"如果游戏中使用了，则播放rep时也需要打开","Need to toggle on when playing rep if used","Need to toggle on when playing rep if used"};
inline constexpr const char* practice_TH_ENABLE_LOCK_TIMER[3]{"启用锁时计时","enable lock timer","enable lock timer"};
inline constexpr const char* practice_TH_FPS_ERR[3]{"FPS调整相关的功能已禁用，你必须满足以下条件之一以使用这些功能：\n1. 使用VsyncPatch，且在vpatch.ini中将”Vsync“一项的值设为0。\n2. 在游戏的custom.exe中将输入方式设置为”高速“。（仅限地灵殿及之后的游戏）","FPS Adjustment related features has been disabled. To enable them, satisfy either of the following requirements:\n1. Use VsyncPatch, and make sure the \"Vsync\" value in vpatch.ini is set to 0.\n2. In the game's custom.exe, set the input method to \"Fast\". (Only applies to SA and after)","FPS調整関連のオプションは無効になっています。 それらを有効にするには、次の要件のいずれかを満たします：\n\n1. VsyncPatchを使用し、vpatch.iniの「Vsync」値を0に設定します。\n2. ゲームのcustom.exeで、入力のレイテンシを「高速」に設定します。 （地霊殿以降のみに適用）"};
inline constexpr const char* practice_TH_FPS_UNSUPPORTED[3]{"不支持的VsyncPatch版本。","Unsupported VsyncPatch version.","このバージョンのVsyncPatchはサポートされていません。"};
inline constexpr const char* practice_TH_FPS_ADJ[3]{"FPS调整","FPS Adjustment","FPS調整"};
inline constexpr const char* practice_TH_FPS_FREE_ADJ[3]{"自由调整","Adjust freely","自由調整"};
inline constexpr const char* practice_TH_ADV_OPT_APPLY[3]{"应用","Apply","変更を適用"};
inline constexpr const char* practice_TH_FPS_LOWERING[3]{"使用VsyncPatch时降低FPS可能会导致游戏冻结一小段时间，请耐心等待。","When using VsyncPatch, lowering FPS may freeze the game for a brief time. Please wait patiently.","VsyncPatchを使用している場合、FPSを下げるとゲームが一時的にフリーズする可能性がありますので、しばらくお待ちください。"};
inline constexpr const char* practice_TH_ADV_DISABLE_X_KEY[3]{"禁用X键","disable X key","disable X key"};
inline constexpr const char* practice_TH_ADV_DISABLE_X_KEY_DESC[3]{"给打nb的人准备(快捷键 shift+D)","for who want to play nb neta(hotkey shift+D)","for who want to play nb neta(hotkey shift+D)"};
inline constexpr const char* practice_TH_ADV_DISABLE_SHIFT_KEY[3]{"禁用Shift键","disable shift key","disable shift key"};
inline constexpr const char* practice_TH_ADV_DISABLE_SHIFT_KEY_DESC[3]{"喜欢低封?(快捷键 shift+A)","like NO FOCUS?(hotkey shift+A)","like NO FOCUS?(hotkey shift+A)"};
inline constexpr const char* practice_TH_ADV_DISABLE_Z_KEY[3]{"禁用Z键","disable Z key","disable Z key"};
inline constexpr const char* practice_TH_ADV_DISABLE_Z_KEY_DESC[3]{"真假...(快捷键 shift+S)","really?(hotkey shift+S)","really?(hotkey shift+S)"};
inline constexpr const char* practice_TH_ADV_DISABLE_C_KEY_SAMETIME[3]{"禁用X同时禁用C键","disable C key at the same time when disable X","disable C key at the same time when disable X"};
inline constexpr const char* practice_TH_ADV_FORCE_SHIFT_KEY[3]{"始终按住Shift键","force press shift key","force press shift key"};
inline constexpr const char* practice_THPRAC_FAST_RETRY[3]{"练习模式快速re","fast retry for prac mode","fast retry for prac mode"};
inline constexpr const char* practice_THPRAC_FAST_RETRY_DESC2[3]{"快捷键: shift+F","hotkey shift+F","hotkey shift+F"};
inline constexpr const char* practice_THPRAC_AUTO_SHOOT[3]{"自动射击","auto shoot","auto shoot"};
inline constexpr const char* practice_THPRAC_KB_OPEN[3]{"打开按键显示","open key monitor","open key monitor"};
inline constexpr const char* practice_THPRAC_KB_RECORD_START[3]{"开始记录APS","start to record APS","start to record APS"};
inline constexpr const char* practice_THPRAC_KB_RECORD_STOP[3]{"停止记录APS","stop recording","stop recording"};
inline constexpr const char* practice_THPRAC_KB_OUTPUT[3]{"导出到游戏文件夹","output to game folder","output to game folder"};
inline constexpr const char* practice_TH_FACTOR_ACB[3]{"总是计入All Clear Bonus","Always factor in the \"All Clear Bonus\"","いつもオールクリアボーナスを加算します"};
inline constexpr const char* practice_TH_FACTOR_ACB_DESC[3]{"开启时，单关练习六面结束后将会计入All Clear Bonus。","If enabled, when practicing stage 6, the \"All Clear Bonus\" will be added to the total score at the end.","有効になっている場合、練習モードのステージ6の終わりに、最終スコアにオールクリアボーナスを加算されます。"};
inline constexpr const char* practice_TH_ABOUT_THPRAC[3]{"关于thprac","About thprac","thpracのバージョン情報"};
inline constexpr const char* practice_TH_ABOUT_VERSION[3]{"thprac 版本 %s","thprac version %s","thprac ver.%s"};
inline constexpr const char* practice_TH_ABOUT_AUTHOR[3]{"作者：Ack","Author: Ack","作者：Ack"};
inline constexpr const char* practice_TH_ABOUT_WEBSITE[3]{"网站：https://github.com/RUEEE/thprac","Website: https://github.com/RUEEE/thprac","ウェブサイト：https://github.com/RUEEE/thprac"};
inline constexpr const char* practice_TH_ABOUT_THANKS[3]{"特别感谢：\n%s","Special thanks: \n%s","スペシャルサンクス：\n%s"};
inline constexpr const char* practice_TH_ABOUT_HIDE_LICENCE[3]{"隐藏许可信息","Hide license info","ライセンス情報を非表示"};
inline constexpr const char* practice_TH_ABOUT_SHOW_LICENCE[3]{"显示许可信息","Show license info","ライセンス情報を表示"};
inline constexpr const char* practice_THPRAC_INFLIVES_MAP[3]{"将锁残修改为不疮","map inf.lives to no continue","map inf.lives to no continue"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST[3]{"反应力测试","reaction test","reaction test"};
inline constexpr const char* practice_TH_ERROR[3]{"错误","Error","エラー"};
inline constexpr const char* practice_TH_REPFIX_SAVE_ERROR_DEST[3]{"未能写入目标文件。","Failed to write to destination file.","ターゲットファイルに書き込めませんでした。"};
inline constexpr const char* practice_TH_REPFIX_SAVE_ERROR_CLEAR_PARAMS[3]{"重置文件的 thprac 数据失败。","Failed to reset file's thprac data.","ファイルの thprac データのリセットに失敗しました。"};
inline constexpr const char* practice_TH_REPFIX_SAVE_SUCCESS[3]{"保存成功","Successfully saved","保存しました"};
inline constexpr const char* practice_TH_REPFIX_SAVE_SUCCESS_DESC[3]{"成功保存replay至：","Successfully saved replay to: ","リプレイは正常に保存されました："};
inline constexpr const char* practice_TH_REPFIX_SAVE_ERROR_PARAMS[3]{"无法将 thprac 数据写入重放文件。","Failed to add thprac data to replay file.","thprac のデータをリプレイファイルに書き込めませんでした。"};
inline constexpr const char* practice_THPRAC_BACK[3]{"返回","Back","戻る"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST[3]{"输入测试","Input test","Input test"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_DINPUT8_FAILED[3]{"无法初始化dinput8","Failed to init DirectInput8","Failed to init DirectInput8"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_MOUSE[3]{"鼠标","Mouse","Mouse"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_ACQUIRING[3]{"创建设备请求","Acquiring","Acquiring"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_OK[3]{"状态: OK","Status: OK","Status: OK"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_MOUSE_DELTA[3]{"鼠标移动","Mouse Delta","Mouse Delta"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_BUTTONS[3]{"按键情况","Buttons","Buttons"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_MOUSE_FAILED[3]{"无法初始化鼠标","Cannot init mouse","Cannot init mouse"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_KEYBOARD[3]{"键盘","Keyboard","Keyboard"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD[3]{"手柄","Gamepad","Gamepad"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_CONNECT[3]{"初始化手柄","Init Gamepad","Init Gamepad"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_TEST_ACQUIRING_GAMEPAD[3]{"无法获取设备,请重连","Cannot acquire device, please reconnect","Cannot acquire device, please reconnect"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_AXES[3]{"手柄轴","Axes","Axes"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_L_STICK[3]{"左摇杆","L-Stick","L-Stick"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_R_STICK[3]{"右摇杆","R-Stick","R-Stick"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_D_PAD[3]{"十字键","D-pad","D-pad"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_TRIGGER[3]{"扳机键/Z","Trigger/Z","Trigger/Z"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_L_STICK_X[3]{"左摇杆/X","L-Stick/X","L-Stick/X"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_L_STICK_Y[3]{"左摇杆/Y","L-Stick/Y","L-Stick/Y"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_R_STICK_X[3]{"右摇杆/X","R-Stick/X","R-Stick/X"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_R_STICK_Y[3]{"右摇杆/Y","R-Stick/Y","R-Stick/Y"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_S1[3]{"额外轴1","Slider1","Slider1"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_S2[3]{"额外轴2","Slider2","Slider2"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_D_PAD_CENTER[3]{"回中","center","center"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_D_PAD_DEG[3]{"角度","deg","deg"};
inline constexpr const char* practice_THPRAC_TOOLS_INPUT_GAMEPAD_NO_GAMEPAD[3]{"没有可用设备, 请先进行初始化","No available device, please init first","No available device, please init first"};
inline constexpr const char* practice_THPRAC_TOOLS_DICE[3]{"杰哥不要啊","Xeno aaaaaa","Xeno aaaaaa"};
inline constexpr const char* practice_THPRAC_TOOLS_DICE_DROP[3]{"丢","drop","drop"};
inline constexpr const char* practice_THPRAC_TOOLS_DICE_NUM[3]{"丢几次","dice num","dice num"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_FROM_FILE[3]{"随机ROLL","ROLL from file","ROLL from file"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_CSV[3]{"读取CSV文件","read csv file","read csv file"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_CSV_DESC[3]{"需要为utf-8格式, 共两列, 分别为名称和权重","need to be utf-8, has a name column and a weight column","need to be utf-8, has a name column and a weight column"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_RANDOM_COLOR[3]{"随机色","random color","random color"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_CLPS[3]{"查看","view","view"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_START[3]{"开ROLL","ROLL","ROLL"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_REMOVE_CUR[3]{"删除roll到的","remove rolled","remove rolled"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLLF_TIME[3]{"转盘时间","time","time"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_DOWN[3]{"按下反应测试(等待变色后按下方向键)","keydown test(wait for color changed then press arrow key)","keydown test(wait for color changed then press arrow key)"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_UP[3]{"弹起反应测试(按下方向键后,等待变色时弹起)","keyup test(press arrow key until color changes)","keyup test(press arrow key until color changes)"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_SHOW_PROC_BAR[3]{"显示等待时间进度条","show wait time progress bar","show wait time progress bar"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_TIME[3]{"测试次数","times for test","times for test"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_BEGIN[3]{"开始测试(快捷键z/shift)","start(hotkey z/shift)","start(hotkey z/shift)"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_TOO_EARLY[3]{"按太快了","too early","too early"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_NEXT_TEST[3]{"再测一次(快捷键z/shift)","next test(hotkey z/shift)","next test(hotkey z/shift)"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_RESULT[3]{"结果","result","result"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_MODE[3]{"模式","mode","mode"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_MODE_DOWN[3]{"按下测试","press time test","press time test"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_MODE_UP[3]{"弹起测试","release time test","release time test"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_MODE_PROGRESSBAR[3]{"显示进度条","with progress bar","with progress bar"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_MODE_NORMAL[3]{"不显示进度条","no progress bar","no progress bar"};
inline constexpr const char* practice_THPRAC_TOOLS_REACTION_TEST_RESULT_AVG[3]{"结果(平均值)","result(avg)","result(avg)"};
inline constexpr const char* practice_THPRAC_GAMEROLL_EENY_MEENY[3]{"查查喵运","Eeny, meeny, miny, moe!","いーにー、みーにー、まいにー、もー！"};
inline constexpr const char* practice_THPRAC_GAMEROLL_ROLL[3]{"查查狗运","ROLL!","ロール！"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_PLAYER[3]{"随机机体","Random shot type","ランダム機体"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_PLAYER_GAME[3]{"游戏","Game","ゲーム"};
inline constexpr const char* practice_THPRAC_TOOLS_ROLL_RESULT[3]{"你随机到了：%s。（右键查看更多选项）","You've rolled: %s. (Right click for more options)","結果：%s。（右クリックで詳細オプションを表示）"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_TURNTO_GAME[3]{"转至游戏页面","Turn to game page","ゲームページに移動"};
inline constexpr const char* practice_THPRAC_GAMES[3]{"游戏","Games","ゲーム"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_GAME[3]{"随机游戏","Random game","ランダムゲーム"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_GAME_PC98[3]{"PC98","PC98","PC98"};
inline constexpr const char* practice_THPRAC_GAMES_MAIN_SERIES[3]{"整数作","Main Series","整数作"};
inline constexpr const char* practice_THPRAC_GAMES_SPINOFF_STG[3]{"小数点作（STG）","Spinoff (Shmup)","小数点作（STG）"};
inline constexpr const char* practice_THPRAC_GAMES_SPINOFF_OTHERS[3]{"小数点作（其他）","Spinoff (Others)","小数点作（その他）"};
inline constexpr const char* practice_THPRAC_TOOLS_RND_TURNTO_PLAYER[3]{"转至随机机体","Turn to random shot type","ランダム機体に移動"};
inline constexpr const char* practice_THPRAC_KILL_ALL_GAME_DONE[3]{"完成，共清除了 %d 个游戏程序","done, cleared %d background game programs","done, cleared %d background game programs"};
inline constexpr const char* practice_THPRAC_TOOLS_APPLY_THPRAC[3]{"应用thprac至正在运行的游戏","Apply thprac to ongoing game","実行中のゲームにthpracを適用します"};
inline constexpr const char* practice_THPRAC_TOOLS_APPLY_THPRAC_DESC[3]{"建议在选择分辨率/全屏的窗口上使用","Suggest using this on the resolution/fullscreen selection window","Suggest using this on the resolution/fullscreen selection window"};
inline constexpr const char* practice_THPRAC_KILL_ALL_GAME[3]{"清理游戏程序","clear game programs","clear game programs"};
inline constexpr const char* practice_THPRAC_KILL_ALL_GAME_ALERT[3]{"请确保你现在不在游戏中","please make sure you are not currently in the game","please make sure you are not currently in the game"};
inline constexpr const char* practice_phase_five[][3]{{"P1","P1","P1"},{"P2","P2","P2"},{"P3","P3","P3"},{"P4","P4","P4"},{"P4狂暴","Rage(P4)","Rage(P4)"},{"P3狂暴","Rage(P3)","Rage(P3)"},{"P2狂暴","Rage(P2)","Rage(P2)"},{"P1狂暴","Rage(P1)","Rage(P1)"}};
inline constexpr const char* practice_phase_four[][3]{{"P1","P1","P1"},{"P2","P2","P2"},{"P3","P3","P3"},{"P4","P4","P4"}};
inline constexpr const char* practice_phase_startset[][3]{{"默认","default start","default start"},{"修改初始位置","init pos change","init pos change"}};
inline constexpr const char* practice_phase_infinite[][3]{{"正常","Normal","普通"},{"无尽模式","Inf mode","Inf mode"}};
inline constexpr const char* practice_phase_wave[][3]{{"默认","default start","default start"},{"初始第二波","wave 2 start","wave 2 start"},{"初始第一波(光速)","wave 1 start(fast)","wave 1 start(fast)"},{"初始第二波(光速)","wave 2 start(fast)","wave 2 start(fast)"}};
inline constexpr const char* practice_tracker_shots[][3]{{"梦 A","Reimu A","Reimu A"},{"梦 B","Reimu B","Reimu B"},{"梦 C","Reimu C","Reimu C"},{"魔 A","Marisa A","Marisa A"},{"魔 B","Marisa B","Marisa B"},{"魔 C","Marisa C","Marisa C"}};
inline constexpr const char* practice_formations[][3]{{"火符","Fire","火符"},{"水符","Water","水符"},{"木符","Wood","木符"},{"金符","Metal","金符"},{"土符","Earth","土符"}};
inline constexpr const char* practice_tracker_difficulties[][3]{{"Easy","Easy","Easy"},{"Normal","Normal","Normal"},{"Hard","Hard","Hard"},{"Lunatic","Lunatic","Lunatic"},{"Extra","Extra","Extra"},{"Phantasm","Phantasm","Phantasm"},{"Overdrive","Overdrive","Overdrive"},{"Lastword","Lastword","Lastword"}};
inline constexpr const char* practice_shot_categories[][3]{{"全部符卡","All Spells","すべてのスペル"},{"梦A","Yakumo Yukari","八云　紫"},{"梦B","Ibuki Suika","伊吹　萃香"},{"梦C","Shameimaru Aya","射命丸　文"},{"魔A","Alice Margatroid","アリス・マーガトロイド"},{"魔B","Patchouli Knowledge","パチュリー・ノーレッジ"},{"魔C","Kawasiro Nitori","河城　にとり"}};
}
